server:
  servlet:
    context-path: /auth
  port: 20000

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauth2?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    password:
    timeout: 8000
    port: 6379
jasypt:
  encryptor:
    password: abc123
